import type { User, AuthResponse } from '@/modules/auth/types';
import type { DashboardData } from '@/modules/dashboard/types';
import type { LearningPathSummary, LearningPathDetail } from '@/modules/learning/types';
import type { CourseDetail } from '@/modules/course/types';

export const USE_MOCK = import.meta.env.VITE_USE_MOCK === 'true';

export const MOCK_TOKEN = 'mock-jwt-token-for-local-testing';

export const mockUser: User = {
  id: 1,
  email: 'learner1@lms.com',
  first_name: 'John',
  last_name: 'Doe',
  full_name: 'John Doe',
  role: 'learner',
  department: 'Engineering',
  gmfc_coins: 450,
  current_badge_level: 'silver',
  total_learning_hours: 24.5,
  current_streak: 5,
  created_at: '2024-01-15T10:00:00Z',
};

export const mockAuthResponse: AuthResponse = {
  token: MOCK_TOKEN,
  user: mockUser,
};

export const mockDashboardData: DashboardData = {
  user: mockUser,
  mandatory_courses: [
    {
      id: 1,
      title: 'Frontend Development Fundamentals',
      description: 'Learn the core concepts of modern frontend development including HTML, CSS, and JavaScript frameworks.',
      category: 'Frontend',
      thumbnail: '',
      is_mandatory: true,
      duration: 480,
      completion_percentage: 75,
      status: 'in_progress',
      enrolled_at: '2024-01-20T08:00:00Z',
    },
    {
      id: 2,
      title: 'TypeScript Mastery',
      description: 'Master TypeScript for building type-safe, scalable applications with confidence.',
      category: 'Programming',
      thumbnail: '',
      is_mandatory: true,
      duration: 360,
      completion_percentage: 0,
      status: 'enrolled',
      enrolled_at: '2024-01-25T09:00:00Z',
    },
  ],
  in_progress_courses: [
    {
      id: 1,
      title: 'Frontend Development Fundamentals',
      description: 'Learn the core concepts of modern frontend development including HTML, CSS, and JavaScript frameworks.',
      category: 'Frontend',
      thumbnail: '',
      is_mandatory: true,
      duration: 480,
      completion_percentage: 75,
      status: 'in_progress',
    },
    {
      id: 3,
      title: 'React Advanced Patterns',
      description: 'Deep dive into advanced React patterns including context, reducers, and performance optimization.',
      category: 'Frontend',
      thumbnail: '',
      is_mandatory: false,
      duration: 300,
      completion_percentage: 40,
      status: 'in_progress',
    },
    {
      id: 4,
      title: 'API Integration Best Practices',
      description: 'Learn how to build robust integrations with RESTful APIs using modern HTTP clients.',
      category: 'Backend',
      thumbnail: '',
      is_mandatory: true,
      duration: 240,
      completion_percentage: 60,
      status: 'in_progress',
    },
  ],
  completed_courses_count: 7,
  certificates: [
    {
      id: 1,
      course_id: 10,
      course_title: 'JavaScript Fundamentals',
      issued_at: '2024-01-10T14:00:00Z',
    },
    {
      id: 2,
      course_id: 11,
      course_title: 'HTML & CSS Basics',
      issued_at: '2023-12-20T10:00:00Z',
    },
  ],
  gmfc_coins: 450,
  current_badge_level: 'silver',
  leaderboard_rank: 12,
  badges: [
    {
      id: 1,
      name: 'First Course',
      description: 'Completed your first course',
      icon: '🎓',
      earned_at: '2023-12-20T10:00:00Z',
    },
    {
      id: 2,
      name: 'Quiz Master',
      description: 'Passed 5 quizzes successfully',
      icon: '🏆',
      earned_at: '2024-01-05T16:00:00Z',
    },
    {
      id: 3,
      name: 'Learning Streak',
      description: 'Maintained a 5-day learning streak',
      icon: '🔥',
      earned_at: '2024-01-22T08:00:00Z',
    },
  ],
  total_learning_hours: 24.5,
  current_streak: 5,
};

// ---- Learning Paths Mock Data ----

export const mockLearningPaths: LearningPathSummary[] = [
  {
    id: 1,
    title: 'Frontend Development Bootcamp',
    description: 'Master modern frontend development with HTML, CSS, JavaScript, TypeScript, and React. This mandatory path covers everything you need to become a proficient frontend developer.',
    is_mandatory: true,
    due_date: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString(), // 5 days from now
    course_count: 4,
    completed_course_count: 1,
    completion_percentage: 45,
    status: 'in_progress',
    assigned_at: '2024-01-15T08:00:00Z',
  },
  {
    id: 2,
    title: 'Backend Engineering Fundamentals',
    description: 'Learn server-side development with Go, REST APIs, databases, and deployment. Required for all engineering team members.',
    is_mandatory: true,
    due_date: new Date(Date.now() + 20 * 24 * 60 * 60 * 1000).toISOString(), // 20 days from now
    course_count: 3,
    completed_course_count: 0,
    completion_percentage: 0,
    status: 'not_started',
    assigned_at: '2024-01-20T08:00:00Z',
  },
  {
    id: 3,
    title: 'Soft Skills & Communication',
    description: 'Enhance your professional communication, presentation, and leadership skills for career growth.',
    is_mandatory: false,
    due_date: null,
    course_count: 3,
    completed_course_count: 1,
    completion_percentage: 35,
    status: 'in_progress',
    assigned_at: '2024-02-01T08:00:00Z',
  },
];

export const mockLearningPathDetails: Record<number, LearningPathDetail> = {
  1: {
    ...mockLearningPaths[0],
    estimated_duration: 1380,
    courses: [
      {
        id: 1,
        title: 'Frontend Development Fundamentals',
        description: 'Learn the core concepts of modern frontend development including HTML, CSS, and JavaScript frameworks.',
        category: 'Frontend',
        thumbnail: '',
        duration: 480,
        completion_percentage: 75,
        status: 'in_progress',
        order: 1,
        lessons_count: 12,
        completed_lessons: 9,
      },
      {
        id: 2,
        title: 'TypeScript Mastery',
        description: 'Master TypeScript for building type-safe, scalable applications with confidence.',
        category: 'Programming',
        thumbnail: '',
        duration: 360,
        completion_percentage: 0,
        status: 'not_started',
        order: 2,
        lessons_count: 10,
        completed_lessons: 0,
      },
      {
        id: 3,
        title: 'React Advanced Patterns',
        description: 'Deep dive into advanced React patterns including context, reducers, and performance optimization.',
        category: 'Frontend',
        thumbnail: '',
        duration: 300,
        completion_percentage: 40,
        status: 'in_progress',
        order: 3,
        lessons_count: 8,
        completed_lessons: 3,
      },
      {
        id: 4,
        title: 'API Integration Best Practices',
        description: 'Learn how to build robust integrations with RESTful APIs using modern HTTP clients.',
        category: 'Backend',
        thumbnail: '',
        duration: 240,
        completion_percentage: 60,
        status: 'in_progress',
        order: 4,
        lessons_count: 6,
        completed_lessons: 4,
      },
    ],
  },
  2: {
    ...mockLearningPaths[1],
    estimated_duration: 960,
    courses: [
      {
        id: 5,
        title: 'Go Programming Basics',
        description: 'Introduction to Go programming language — syntax, types, concurrency, and tooling.',
        category: 'Backend',
        thumbnail: '',
        duration: 360,
        completion_percentage: 0,
        status: 'not_started',
        order: 1,
        lessons_count: 10,
        completed_lessons: 0,
      },
      {
        id: 6,
        title: 'RESTful API Design',
        description: 'Design and build production-ready REST APIs following industry best practices.',
        category: 'Backend',
        thumbnail: '',
        duration: 300,
        completion_percentage: 0,
        status: 'not_started',
        order: 2,
        lessons_count: 8,
        completed_lessons: 0,
      },
      {
        id: 7,
        title: 'PostgreSQL & Database Design',
        description: 'Master relational database design, SQL queries, and PostgreSQL administration.',
        category: 'Database',
        thumbnail: '',
        duration: 300,
        completion_percentage: 0,
        status: 'not_started',
        order: 3,
        lessons_count: 9,
        completed_lessons: 0,
      },
    ],
  },
  3: {
    ...mockLearningPaths[2],
    estimated_duration: 540,
    courses: [
      {
        id: 8,
        title: 'Effective Business Communication',
        description: 'Learn to communicate clearly and persuasively in professional settings.',
        category: 'Soft Skills',
        thumbnail: '',
        duration: 180,
        completion_percentage: 100,
        status: 'completed',
        order: 1,
        lessons_count: 6,
        completed_lessons: 6,
      },
      {
        id: 9,
        title: 'Presentation Skills Workshop',
        description: 'Build confidence in public speaking and creating impactful presentations.',
        category: 'Soft Skills',
        thumbnail: '',
        duration: 180,
        completion_percentage: 30,
        status: 'in_progress',
        order: 2,
        lessons_count: 5,
        completed_lessons: 1,
      },
      {
        id: 10,
        title: 'Leadership Foundations',
        description: 'Develop core leadership skills for team management and decision making.',
        category: 'Leadership',
        thumbnail: '',
        duration: 180,
        completion_percentage: 0,
        status: 'not_started',
        order: 3,
        lessons_count: 7,
        completed_lessons: 0,
      },
    ],
  },
};

// ---- Course Detail Mock Data ----

export const mockCourseDetails: Record<number, CourseDetail> = {
  1: {
    id: 1,
    title: 'Frontend Development Fundamentals',
    description: 'Learn the core concepts of modern frontend development including HTML, CSS, and JavaScript frameworks. This comprehensive course covers semantic HTML, modern CSS layouts (Flexbox, Grid), responsive design, and vanilla JavaScript fundamentals that form the basis of all frontend frameworks.',
    category: 'Frontend',
    thumbnail: '',
    duration: 480,
    is_mandatory: true,
    completion_percentage: 75,
    status: 'in_progress',
    enrolled_at: '2024-01-20T08:00:00Z',
    lessons_count: 12,
    completed_lessons: 9,
    modules: [
      {
        id: 1,
        title: 'HTML Foundations',
        order: 1,
        lessons: [
          { id: 1, title: 'Introduction to HTML5', type: 'video', duration: 30, order: 1, is_completed: true },
          { id: 2, title: 'Semantic HTML Elements', type: 'video', duration: 25, order: 2, is_completed: true },
          { id: 3, title: 'Forms and Validation', type: 'video', duration: 35, order: 3, is_completed: true },
          { id: 4, title: 'HTML Knowledge Check', type: 'quiz', duration: 15, order: 4, is_completed: true },
        ],
      },
      {
        id: 2,
        title: 'CSS Mastery',
        order: 2,
        lessons: [
          { id: 5, title: 'CSS Selectors & Specificity', type: 'video', duration: 40, order: 1, is_completed: true },
          { id: 6, title: 'Flexbox Layout', type: 'video', duration: 45, order: 2, is_completed: true },
          { id: 7, title: 'CSS Grid Layout', type: 'video', duration: 45, order: 3, is_completed: true },
          { id: 8, title: 'Responsive Design Patterns', type: 'document', duration: 20, order: 4, is_completed: true },
        ],
      },
      {
        id: 3,
        title: 'JavaScript Essentials',
        order: 3,
        lessons: [
          { id: 9, title: 'Variables, Types & Functions', type: 'video', duration: 50, order: 1, is_completed: true },
          { id: 10, title: 'DOM Manipulation', type: 'video', duration: 45, order: 2, is_completed: false },
          { id: 11, title: 'Async JavaScript (Promises, Async/Await)', type: 'video', duration: 55, order: 3, is_completed: false },
          { id: 12, title: 'Final Assessment', type: 'quiz', duration: 30, order: 4, is_completed: false },
        ],
      },
    ],
    materials: [
      { id: 1, name: 'HTML5 Cheat Sheet', type: 'pdf', size: 245000, url: '/materials/html5-cheatsheet.pdf' },
      { id: 2, name: 'CSS Grid Guide', type: 'pdf', size: 380000, url: '/materials/css-grid-guide.pdf' },
      { id: 3, name: 'JavaScript ES6+ Reference', type: 'pdf', size: 520000, url: '/materials/js-es6-reference.pdf' },
      { id: 4, name: 'Course Slides', type: 'ppt', size: 2400000, url: '/materials/frontend-fundamentals-slides.pptx' },
    ],
  },
  3: {
    id: 3,
    title: 'React Advanced Patterns',
    description: 'Deep dive into advanced React patterns including context, reducers, performance optimization, and modern state management. Learn to build scalable React applications with proven architectural patterns.',
    category: 'Frontend',
    thumbnail: '',
    duration: 300,
    is_mandatory: false,
    completion_percentage: 40,
    status: 'in_progress',
    enrolled_at: '2024-02-01T10:00:00Z',
    lessons_count: 8,
    completed_lessons: 3,
    modules: [
      {
        id: 4,
        title: 'State Management Patterns',
        order: 1,
        lessons: [
          { id: 13, title: 'useReducer for Complex State', type: 'video', duration: 35, order: 1, is_completed: true },
          { id: 14, title: 'Context API Deep Dive', type: 'video', duration: 40, order: 2, is_completed: true },
          { id: 15, title: 'State Management Quiz', type: 'quiz', duration: 15, order: 3, is_completed: true },
        ],
      },
      {
        id: 5,
        title: 'Performance Optimization',
        order: 2,
        lessons: [
          { id: 16, title: 'React.memo & useMemo', type: 'video', duration: 40, order: 1, is_completed: false },
          { id: 17, title: 'Code Splitting & Lazy Loading', type: 'video', duration: 35, order: 2, is_completed: false },
          { id: 18, title: 'React Profiler & DevTools', type: 'video', duration: 30, order: 3, is_completed: false },
        ],
      },
      {
        id: 6,
        title: 'Compound Components',
        order: 3,
        lessons: [
          { id: 19, title: 'Compound Component Pattern', type: 'video', duration: 45, order: 1, is_completed: false },
          { id: 20, title: 'Final Project', type: 'document', duration: 60, order: 2, is_completed: false },
        ],
      },
    ],
    materials: [
      { id: 5, name: 'React Patterns Handbook', type: 'pdf', size: 680000, url: '/materials/react-patterns.pdf' },
      { id: 6, name: 'Performance Checklist', type: 'doc', size: 120000, url: '/materials/perf-checklist.docx' },
    ],
  },
  5: {
    id: 5,
    title: 'Go Programming Basics',
    description: 'Introduction to Go programming language — syntax, types, concurrency, and tooling. Build your first Go applications and understand the language philosophy.',
    category: 'Backend',
    thumbnail: '',
    duration: 360,
    is_mandatory: true,
    completion_percentage: 0,
    status: 'not_started',
    enrolled_at: null,
    lessons_count: 10,
    completed_lessons: 0,
    modules: [
      {
        id: 7,
        title: 'Getting Started with Go',
        order: 1,
        lessons: [
          { id: 21, title: 'Installing Go & Workspace Setup', type: 'video', duration: 20, order: 1, is_completed: false },
          { id: 22, title: 'Hello World & Basic Syntax', type: 'video', duration: 30, order: 2, is_completed: false },
          { id: 23, title: 'Variables, Types & Constants', type: 'video', duration: 35, order: 3, is_completed: false },
        ],
      },
      {
        id: 8,
        title: 'Control Flow & Data Structures',
        order: 2,
        lessons: [
          { id: 24, title: 'Conditionals & Loops', type: 'video', duration: 30, order: 1, is_completed: false },
          { id: 25, title: 'Arrays, Slices & Maps', type: 'video', duration: 40, order: 2, is_completed: false },
          { id: 26, title: 'Structs & Interfaces', type: 'video', duration: 45, order: 3, is_completed: false },
          { id: 27, title: 'Data Structures Quiz', type: 'quiz', duration: 15, order: 4, is_completed: false },
        ],
      },
      {
        id: 9,
        title: 'Concurrency in Go',
        order: 3,
        lessons: [
          { id: 28, title: 'Goroutines & Channels', type: 'video', duration: 50, order: 1, is_completed: false },
          { id: 29, title: 'Concurrency Patterns', type: 'video', duration: 45, order: 2, is_completed: false },
          { id: 30, title: 'Final Assessment', type: 'quiz', duration: 30, order: 3, is_completed: false },
        ],
      },
    ],
    materials: [
      { id: 7, name: 'Go Language Cheat Sheet', type: 'pdf', size: 310000, url: '/materials/go-cheatsheet.pdf' },
      { id: 8, name: 'Go Best Practices Guide', type: 'pdf', size: 450000, url: '/materials/go-best-practices.pdf' },
    ],
  },
};
